# Generated by Django 2.1.8 on 2019-05-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m_size', models.BigIntegerField()),
                ('n_size', models.BigIntegerField()),
                ('l_size', models.BigIntegerField()),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('average_time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.Algorithm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
